### PR TITLE
Support for custom config classes

### PR DESCRIPTION
**Pull request by solnic**

### CODE REVIEW

**Comment by solnic** [comment]
@timriley bump :)

**Comment by timriley** [comment]
@solnic This is looking good to me so far! Feels like it'd be worth following through in this PR to support custom config classes on nested settings, because without that, this single "outer" custom config class may be of fairly limited value (i.e. I know we couldn't port Hanami::Action's configuration to vanilla dry-configurable at that point; we'd need the custom nested config classes too).

**Comment by solnic** [comment]
@timriley you mean something like this:

```ruby
setting :db do
  setting :host, config: MyHostConfig do
    # ...
  end
end
```

??

**Comment by timriley** [comment]
@solnic yep, exactly this!

**Comment by solnic** [comment]
@timriley OK I'll make it possible in this PR

**Comment by solnic** [comment]
@timriley I called the option `config_class` to avoid confusion with the actual config instance. Looks like things are working 🙂

**Comment by timriley** [comment]
@solnic Looks great! And I agree on `config_class` being a clearer name.

Let's get this merged! Huge improvement for dry-configurable! 🎉 

Once this is merged I'll update #138 to fit with the new structure.

**Review by timriley — APPROVED** [review]

**Pull request merged**
